---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vgpu-device-manager
  namespace: default
  labels:
    app: vgpu-device-manager
spec:
  selector:
    matchLabels:
      app: vgpu-device-manager
  template:
    metadata:
      labels:
        app: vgpu-device-manager
    spec:
      serviceAccount: vgpu-device-manager
      serviceAccountName: vgpu-device-manager
      containers:
      - name: vgpu-device-manager
        image: nvcr.io/nvidia/cloud-native/vgpu-device-manager:v0.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          value: "default"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONFIG_FILE
          value: "/vgpu-devices-config/config.yaml"
        - name: DEFAULT_VGPU_CONFIG
          value: "default"
        - name: GPU_CLIENTS_FILE
          value: "/gpu-clients/clients.yaml"
        - name: LD_PRELOAD
          value: "/driver-root/usr/lib64/libnvidia-ml.so.1"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /vgpu-devices-config
          name: vgpu-devices-config
        - mountPath: /gpu-clients
          name: gpu-clients
        - name: driver-install-dir
          mountPath: /driver-root
          mountPropagation: HostToContainer
        - mountPath: /sys
          name: host-sys
        - mountPath: /host
          name: host-root

      volumes:
      - name: vgpu-devices-config
        configMap:
          name: vgpu-devices-config
      - name: gpu-clients
        configMap:
          name: gpu-clients
      - name: driver-install-dir
        hostPath:
          path: "/run/nvidia/driver"
          type: DirectoryOrCreate
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
      - name: host-root
        hostPath:
          path: /
          type: Directory

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vgpu-device-manager
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vgpu-device-manager
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  verbs:
  - get
  - list
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vgpu-device-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vgpu-device-manager
subjects:
- kind: ServiceAccount
  name: vgpu-device-manager
  namespace: default
